### checking cpu info 

In [2]:
#!lscpu
#!free -m # to check ram in MB
! df -h  # to check hard usage

Filesystem      Size  Used Avail Use% Mounted on
overlay          31G   17G   12G  59% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/root        29G   22G  7.9G  73% /usr/sbin/docker-init
/dev/sdb1       118G  2.5M  112G   1% /tmp
/dev/loop3       31G   17G   12G  59% /workspaces


In [4]:
# checking tensorflow 
! pip install tensorflow 
! pip list | grep -i tensorflow 

tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.33.0


In [7]:
# checking version
import tensorflow as tf
print(tf.__version__)

2.13.0


In [9]:
# creating tensor vector 
x = tf.constant([1,2,3]) # creatign 
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [16]:
# inbuild function using 
y=tf.ones((4,4),dtype='int32')
y1=tf.ones((3,3),dtype=tf.int64)
y2=tf.zeros((2,3))
y3=tf.eye(3) # identity matrix 
y4=tf.range(start=2,limit=20,delta=2)
print(y4)

tf.Tensor([ 2  4  6  8 10 12 14 16 18], shape=(9,), dtype=int32)


In [17]:
# maths is same as numpy 
x1=tf.constant([2,3,4])
x2=tf.constant([5,8,4])
z1=tf.add(x1,x2) # created 3 vector 
print(z1)

tf.Tensor([ 7 11  8], shape=(3,), dtype=int32)
